---
- name: "Deploy files from Git repository"
  git:
    repo: "https://github.com/digiwhist/opentender.git"
    dest: "{{opentender.dir}}"
    force: yes

- name: Changing perm of "{{opentender.dir}}/setup/setup.sh", adding "+x"
  file: dest={{opentender.dir}}/setup/setup.sh mode=a+x

- name: "Call install script"
  shell: "{{opentender.dir}}/setup/setup.sh"
  args:
    chdir: "{{opentender.dir}}/setup"

- name: "Set opentender user permissions"
  file:
    dest: "{{opentender.dir}}"
    owner: "{{system.user}}"
    group: "{{system.group}}"
    state: directory
    recurse: yes
