---
- name: "Setup Opentender Server"
  hosts: opentender
  remote_user: root
  roles:
    - check/server
    - setup/disable-passwort-login
    - setup/apt-update
    - setup/basics
    - setup/mail
    - install/java
    - install/elasticsearch
    - install/node
    - install/pm2
    - install/opentender
    - install/tenderapivpn
#    - deploy/letsencrypt
#    - deploy/memcached
#    - deploy/nginx
#    - deploy/opentender
